[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ["py311", "py312", "py313", "py314"]
skip-string-normalization = true

[tool.isort]
known_first_party = ["tifffile"]
profile = "black"
line_length = 79
